## =================== DESCRIPTION ===================
Description: >-
  AWS CloudFormation sample template 
  Playground for 'Conditions' section - using 'AWS::NoValue'
  Attach SecurityGroups to EC2 instance conditionally:
  - if PROD then attach
  - otherwise (if DEV) then ingnore

## =================== PARAMETERS ===================
Parameters:
  paramEnvironment: # ask a user to define whether it is 'dev' or 'prod' environment
    Description: Select the environment 
    Type: String
    Default: dev # by default it is 'dev' environment
    AllowedValues: 
      - dev
      - prod
    ConstraintDescription: Must be development or production 

## =================== CONDITIONS ===================
Conditions:
  isProd: !Equals [!Ref paramEnvironment, prod] # if 'prod' then TRUE, otherwise FALSE       

## =================== RESOURCES ===================
Resources:
  
  myEC2Instance: # create a new EC2 instance
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0ff8a91507f77f867'  
      InstanceType: !If [isProd, t2.micro,  t1.nano ] # if 'prod' then t2.micro, otherwise t2.nano 
      SecurityGroups: !If [isProd, [!Ref myHTTPSSecurityGroup], !Ref 'AWS::NoValue'] # if PROD then attach SecurityGroups, otherwise ignore

  myHTTPSSecurityGroup: # create a new Security Group for HTTPS only if PROD
    Type: 'AWS::EC2::SecurityGroup'
    Condition: isProd
    Properties:
      GroupDescription: Enable HTTPS access via port 443
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp:  0.0.0.0/0