## =================== DESCRIPTION ===================
Description: >-
  AWS CloudFormation sample template. 
  Playground for 'Conditions' section - Attach SecurityGroups to EC2 instance conditionally (if PROD only)

## =================== PARAMETERS ===================
Parameters:
  paramEnvironment: # ask a user to define whether it is 'dev' or 'prod' environment
    Description: Select the environment 
    Type: String
    Default: dev # by default it is 'dev' environment
    AllowedValues: 
      - dev
      - prod
    ConstraintDescription: Must be development or production 

## =================== CONDITIONS ===================
Conditions:
  isProd: !Equals [!Ref paramEnvironment, prod] # if 'prod' then TRUE, otherwise FALSE       

## =================== RESOURCES ===================
Resources:
  myEC2Instance: # create a new EC2 instance
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0ff8a91507f77f867'  
      InstanceType: !If [isProd, t2.micro,  t1.micro ] # if 'prod', then t2.micro, (else) if 'dev' then t2.nano otherwise (if 'qa') then t1.micro  
      SecurityGroups: !If [isProd, [!Ref myHTTPSSecurityGroup], !Ref 'AWS::NoValue'] # if PROD only then attach SecurityGroups 

  myHTTPSSecurityGroup: # if PROD then create a new Security Group for HTTPS
    Type: 'AWS::EC2::SecurityGroup'
    Condition: isProd
    Properties:
      GroupDescription: Enable HTTPS access via port 443
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp:  0.0.0.0/0