AWSTemplateFormatVersion: '2010-09-09'

## =================== DESCRIPTION =================== ##
Description: >-
  AWS CloudFormation template 
  Playground for 'userDataAndMetadata'
  Step 0. Follow README in '0-source-code' folder to create S3 bucket and upload source code there
  Step 1. Create EC2 intance with attached SG (with SSH and HTTP ports) 

## =================== PARAMETERS =================== ##
Parameters:
  paramEC2KeyPair:
    Description: Specify an EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName

## =================== RESOURCES =================== ##
Resources:
  
  myEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      # Kalyan Reddy: If you are using  Linux AMI 2-series, mostly it might not work because AWS has done lot and lot of changes from AMI-1 to AMI-2 series VMs
      #ImageId: ami-047a51fa27710816e # amzn2-ami-hvm-2.0.20210126.0-x86_64-gp2 - ami-047a51fa27710816e - Amazon Linux 2 AMI 2.0.20210126.0 x86_64 HVM gp2, free tier eligible
      ImageId:  ami-0080e4c5bc078760e # amzn-ami-hvm-2018.03.0.20181129-x86_64-gp2 - Amazon Linux AMI 2018.03.0.20181129 x86_64 HVM gp2
      InstanceType: t2.micro # free tier eligible
      KeyName: !Ref paramEC2KeyPair
      SecurityGroups: 
        - !Ref mySecurityGroup

  mySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and HTTP access via port 22 and 8080
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0